@startuml

note right
    黄色表示有交互数据库的操作
    红色表示跟keycloak服务有交互的操作
end note
start
:解析、校验参数;
if (token无效?) then (yes)
    :提示token失效;
    stop
endif
#yellow:查询用户id在传参的数组中的邀请记录，并且以user_id分组，统计计数;
:返回结果数据;
stop
@enduml