@startuml
note right
    黄色表示有交互数据库的操作
    红色表示跟keycloak服务有交互的操作
end note
start
:解析、校验参数;
if (token无效?) then (yes)
    :提示token失效;
    stop
endif
#yellow:根据用户id获取用户记录;
:切分钱包地址字段，转换为地址数组;
#yellow:根据钱包地址，查询绑定关系记录;
if (关系记录存在?) then (yes)
    if (关系记录数 == 钱包地址数量?) then (yes)
    :返回错误，提示钱包已经绑定;
    note left
        这里不做判断，是否绑定的用户是自己还是别人，
        统一返回已绑定错误
    end note
    else (no)
        :过滤出没有绑定的钱包地址;
        #yellow:插入未绑定钱包的关系记录;
        #green:(异步)转换sca地址;
    endif
    stop
else (no)
    #yellow:插入绑定关系记录;
    #green:(异步)转换sca地址;
    :返回成功;
endif
stop
@enduml